### PR TITLE
Big update on UpdateCustomDataFields.m

### PR DESCRIPTION
**Pull request by tsgouvea**
- Removed `OutcomeRecord` field from data structure `BpodSystem.Data.Custom`. Trial outcome can be inferred from fields containing boolean vectors such as `ChoiceCorrect`, `Rewarded`, `Feedback`, `FixBroke`, etc.
- Vectors in data fields indexed by `iTrial`, rather than relative indices such as `end` or `end+1`.
- GUI parameters are saved to the data structure, but they're read into the state matrix directly from the GUI-related variable `TaskParameters` (commonly named `S` in other Bpod protocols). They were read from the data structure before.
- Fits a logistic regression to psychometric curve, and plots different reward blocks separately.

### CODE REVIEW

**Comment by torbenott** [comment]
Great! I think that's a very nice improvement to the structure of especially Olf2AFC.m and updateCustomDataFields. Just to let you know, I probably won't be able to re-check every line for correct performance. I read everything through and I'll make some general checks.

**Comment by tsgouvea** [comment]
Latest commits:
- 7c5c4eb implements random reward for boundary stimulus (amended by 11b5581). 
- cbbb093 In case FeedbackDelay is set to random, and the animal fails it in one trial, the same value will be reused in the following trial (as opposed to drawing a new random value). This is aimed at preventing animals from "discarding" delays on the long end by aborting those trials.

**Comment by torbenott** [comment]
cbbb093: I haven't commented on the issue yet because it's not obvious to me at all that this is the strategy to go. I wanted to have a live discussion with several people on that first or make it optional if you know you want to have it. my concern is that if the animals are forced to wait - what will they do on catch trials? It might massively skew the cost function and thus waiting time distributions

**Comment by tsgouvea** [comment]
Fair enough. I did not consider the impact on the wagering task. It wasn't a big deal for me anyway, so I'm cool with leaving it out (i.e. reversing cbbb093).

**Pull request merged**
